language: ruby

rvm:
  - 1.9.3

before_install:
  - gem update --system

before_script:
  - mysql -e 'create database powerdns-spec;'
  - mysql powerdns-spec < misc/powerdns.mysql

#script: "bundle exec rake"

gemfile:
  - Gemfile

branches:
  only:
    - master
